trigger:
- main  # Change to your target branch

pool:
  vmImage: 'ubuntu-latest'  # Use an agent with Bash and Azure CLI pre-installed
  
parameters:
- name: customer
  type: string
  default: 'demo'  # Default value if not provided

variables:
  SCRIPT_PATH: './account-nodered-deploy.sh'

stages:
- stage: Deploy
  jobs:
  - job: RunShellScript
    steps:
    - checkout: self  # Checkout the repository

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        inlineScript: |
          bash $(SCRIPT_PATH) ${{ parameters.customer }}
      displayName: 'Run Deployment Script'

