trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)
  DOCKERHUB_PASSWORD: $(DOCKERHUB_PASSWORD)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image
    jobs:
      - job: BuildAndPushImage
        displayName: Build and Push Node-RED Docker Image
        steps:
          - checkout: self

          - task: Cache@2
            inputs:
              key: 'buildx-cache-$(Build.SourceVersion)'
              path: '/tmp/.buildx-cache'
              restoreKeys: |
                buildx-cache-

          - script: |
              docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            displayName: 'Set up QEMU'

          - script: |
              docker buildx create --use
            displayName: 'Set up Docker Buildx'

          - task: Docker@2
            displayName: 'Login to Docker Hub'
            inputs:
              command: login
              containerRegistry: 'https://index.docker.io/v1/'
              username: $(DOCKERHUB_USERNAME)
              password: $(DOCKERHUB_PASSWORD)

          - script: |
              docker buildx build \
                --platform linux/amd64,linux/arm64/v8 \
                --cache-from type=local,src=/tmp/.buildx-cache \
                --cache-to type=local,dest=/tmp/.buildx-cache \
                --push \
                -t dsamborschi42/zemfyre-node-red:latest \
                -f ./nodered/Dockerfile .
            displayName: 'Build and Push Docker Image'

